# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: rabbit
      labels:
        app: rabbit
        kube-monkey/enabled: enabled
        kube-monkey/identifier: rabbit
        kube-monkey/mtbf: '1'
    spec:
      containers:
      - name: rabbit
        image: rabbitmq:3.6-management
        imagePullPolicy: Always
        ports:
        - containerPort: 15672
          name: rabbit-http
          protocol: TCP
        - containerPort: 5672
          name: rabbit-amqp
          protocol: TCP
        - containerPort: 25672
          name: rabbit-cluster
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
